version: '3.7'

services:
  web:
    build:
      context: ./project
      dockerfile: Dockerfile.prod
    command: gunicorn project_folder.wsgi:application --bind 0.0.0.0:8000
    volumes:
       - static_volume:/home/project/web/staticfiles
       - media_volume:/home/project/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    build: ./db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    volumes:
       -  static_volume:/home/project/web/staticfiles
       -  media_volume:/home/project/web/mediafiles
       - ./data/certbot/conf:/etc/letsencrypt
       - ./data/certbot/www:/var/www/certbot   
    ports:
      - 80:8080
      - 443:8443
    depends_on:
      - web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:
  static_volume:
  media_volume:
