# Generated by Django 3.0.4 on 2020-04-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Text for meta tag description and social cards (SEO)', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_bn',
            field=models.TextField(blank=True, help_text='Text for meta tag description and social cards (SEO)', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='Text for meta tag description and social cards (SEO)', null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_es',
            field=models.TextField(blank=True, help_text='Text for meta tag description and social cards (SEO)', null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='internal_notes',
            field=models.TextField(blank=True, help_text="A place to leave notes &ndash; this won't show up on page.", null=True),
        ),
    ]
